data:
  Far-Near:
    Lytro:
      lytro-01: 32
      lytro-02: 32
      lytro-03: 32
      lytro-04: 32
      lytro-05: 32
      lytro-06: 32
      lytro-07: 32
      lytro-08: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
      lytro-01: 32
