data:
  Far-Near:
    Lytro:
      lytro-01: 30
      lytro-02: 30
      lytro-03: 30
      lytro-04: 30
      lytro-05: 30
      lytro-06: 30
      lytro-07: 30
      lytro-08: 30
      lytro-09: 30
      lytro-10: 30
      lytro-11: 30
      lytro-12: 30
      lytro-13: 30
      lytro-14: 30
      lytro-15: 30
      lytro-16: 30
      lytro-17: 30
      lytro-18: 30
      lytro-19: 30
      lytro-20: 30
